# EDA via PyCaret  

Tutorial pages: https://pycaret.gitbook.io/docs/get-started/tutorials  
Binary Classification page: https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb

In [3]:
from pycaret.regression import *
import pandas as pd
from sklearn.model_selection import train_test_split
from config import *

In [4]:
df=pd.read_csv(INTERIM_DIR+'/tmp_df.csv')
df.tail()

,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Cancer Type Detailed,Cellularity,Chemotherapy,Pam50 + Claudin-low subtype,Cohort,ER status measured by IHC,ER Status,Neoplasm Histologic Grade,HER2 status measured by SNP6,HER2 Status,Tumor Other Histologic Subtype,Hormone Therapy,Inferred Menopausal State,Integrative Cluster,Primary Tumor Laterality,Lymph nodes examined positive,Mutation Count,Nottingham prognostic index,Overall Survival (Months),Overall Survival Status,PR Status,Radio Therapy,Relapse Free Status (Months),Relapse Free Status,3-Gene classifier subtype,TMB (nonsynonymous),Tumor Size,Tumor Stage,Patient's Vital Status
1980,43.10,BREAST CONSERVING,Breast Cancer,Breast Invasive Lobular Carcinoma,High,NO,LumA,4.0,Positve,Positive,3.0,NEUTRAL,Negative,Lobular,YES,Pre,3,Right,1.0,4.0,5.05,196.866667,0:LIVING,Positive,YES,194.28,0:Not Recurred,ER+/HER2- Low Prolif,5.230071,25.0,NaN,Living
1981,42.88,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,High,NO,LumB,4.0,Positve,Positive,3.0,GAIN,Positive,Ductal/NST,NO,Pre,5,NaN,1.0,6.0,5.04,44.733333,1:DECEASED,Negative,YES,16.09,1:Recurred,NaN,7.845106,20.0,NaN,Died of Disease
1982,62.90,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,High,NO,LumB,4.0,Positve,Positive,3.0,NEUTRAL,Negative,Ductal/NST,YES,Post,1,Left,45.0,4.0,6.05,175.966667,1:DECEASED,Positive,YES,121.18,1:Recurred,NaN,5.230071,25.0,NaN,Died of Disease
1983,61.16,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,Moderate,NO,LumB,4.0,Positve,Positive,2.0,NEUTRAL,Negative,Ductal/NST,YES,Post,1,NaN,12.0,15.0,5.05,86.233333,1:DECEASED,Positive,NO,85.10,0:Not Recurred,ER+/HER2- High Prolif,19.612766,25.0,NaN,Died of Other Causes
1984,60.02,BREAST CONSERVING,Breast Cancer,Breast Invasive Ductal Carcinoma,High,NO,LumB,4.0,Positve,Positive,3.0,NEUTRAL,Negative,Ductal/NST,YES,Post,10,NaN,1.0,3.0,5.04,201.900000,1:DECEASED,Negative,YES,199.24,0:Not Recurred,ER+/HER2- High Prolif,3.922553,20.0,NaN,Died of Other Causes

In [17]:
df.columns

Index(['Age at Diagnosis', 'Type of Breast Surgery', 'Cancer Type',
       'Cancer Type Detailed', 'Cellularity', 'Chemotherapy',
       'Pam50 + Claudin-low subtype', 'Cohort', 'ER status measured by IHC',
       'ER Status', 'Neoplasm Histologic Grade',
       'HER2 status measured by SNP6', 'HER2 Status',
       'Tumor Other Histologic Subtype', 'Hormone Therapy',
       'Inferred Menopausal State', 'Integrative Cluster',
       'Primary Tumor Laterality', 'Lymph nodes examined positive',
       'Mutation Count', 'Nottingham prognostic index',
       'Overall Survival (Months)', 'Overall Survival Status', 'PR Status',
       'Radio Therapy', 'Relapse Free Status (Months)', 'Relapse Free Status',
       '3-Gene classifier subtype', 'TMB (nonsynonymous)', 'Tumor Size',
       'Tumor Stage', 'Patient's Vital Status'],
      dtype='object')

# columns 対応表

|metabric.csv|outcome.csv|
|-|-|
|Overall Survival Status|OS_STATUS|
|Overall Survival (Months)|OS_MONTHS|
|Relapse Free Status|RFS_STATUS|
|Relapse Free Status (Months)|RFS_MONTHS|
|Patient's Vital Status|VITAL_STATUS|

In [18]:
# drop outcome candidate
drop_columns = [
    'Overall Survival Status',
    #'Overall Survival (Months)',
    'Relapse Free Status',
    'Relapse Free Status (Months)',
    "Patient's Vital Status"
]
df_caret=df.drop(drop_columns,axis=1)
df_caret.columns

Index(['Age at Diagnosis', 'Type of Breast Surgery', 'Cancer Type',
       'Cancer Type Detailed', 'Cellularity', 'Chemotherapy',
       'Pam50 + Claudin-low subtype', 'Cohort', 'ER status measured by IHC',
       'ER Status', 'Neoplasm Histologic Grade',
       'HER2 status measured by SNP6', 'HER2 Status',
       'Tumor Other Histologic Subtype', 'Hormone Therapy',
       'Inferred Menopausal State', 'Integrative Cluster',
       'Primary Tumor Laterality', 'Lymph nodes examined positive',
       'Mutation Count', 'Nottingham prognostic index',
       'Overall Survival (Months)', 'PR Status', 'Radio Therapy',
       '3-Gene classifier subtype', 'TMB (nonsynonymous)', 'Tumor Size',
       'Tumor Stage'],
      dtype='object')

# PyCaret models
PyCaretを使用し、簡単にデータの傾向と予測の関係性を見てみる

In [19]:
train_X, test_X= train_test_split(df_caret, test_size=0.25, random_state=0)

In [21]:
exp_clf101=setup(train_X, target='Overall Survival (Months)', session_id=1)

In [22]:
best = compare_models(exclude = ['ransac'])

In [24]:
models()

,Name,Reference,Turbo
ID,,,
lr,Linear Regression,sklearn.linear_model._base.LinearRegression,True
lasso,Lasso Regression,sklearn.linear_model._coordinate_descent.Lasso,True
ridge,Ridge Regression,sklearn.linear_model._ridge.Ridge,True
en,Elastic Net,sklearn.linear_model._coordinate_descent.Elast...,True
lar,Least Angle Regression,sklearn.linear_model._least_angle.Lars,True
llar,Lasso Least Angle Regression,sklearn.linear_model._least_angle.LassoLars,True
omp,Orthogonal Matching Pursuit,sklearn.linear_model._omp.OrthogonalMatchingPu...,True
br,Bayesian Ridge,sklearn.linear_model._bayes.BayesianRidge,True
ard,Automatic Relevance Determination,sklearn.linear_model._bayes.ARDRegression,False
par,Passive Aggressive Regressor,sklearn.linear_model._passive_aggressive.Passi...,True
ransac,Random Sample Consensus,sklearn.linear_model._ransac.RANSACRegressor,False
tr,TheilSen Regressor,sklearn.linear_model._theil_sen.TheilSenRegressor,False
huber,Huber Regressor,sklearn.linear_model._huber.HuberRegressor,True
kr,Kernel Ridge,sklearn.kernel_ridge.KernelRidge,False
svm,Support Vector Regression,sklearn.svm._classes.SVR,False
knn,K Neighbors Regressor,sklearn.neighbors._regression.KNeighborsRegressor,True
dt,Decision Tree Regressor,sklearn.tree._classes.DecisionTreeRegressor,True
rf,Random Forest Regressor,sklearn.ensemble._forest.RandomForestRegressor,True
et,Extra Trees Regressor,sklearn.ensemble._forest.ExtraTreesRegressor,True
ada,AdaBoost Regressor,sklearn.ensemble._weight_boosting.AdaBoostRegr...,True
gbr,Gradient Boosting Regressor,sklearn.ensemble._gb.GradientBoostingRegressor,True
mlp,MLP Regressor,sklearn.neural_network._multilayer_perceptron....,False
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBRegressor,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMRegressor,True
dummy,Dummy Regressor,sklearn.dummy.DummyRegressor,True

In [25]:
ada=create_model('ada')

In [26]:
ada

AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=50, random_state=1)

In [38]:
lightgbm=create_model('lightgbm')

In [28]:
tuned_ada=tune_model(ada)

In [32]:
evaluate_model(tuned_ada)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [33]:
predict_model(tuned_ada);

In [34]:
final_ada = finalize_model(tuned_ada)
print(final_ada)

AdaBoostRegressor(base_estimator=None, learning_rate=0.05, loss='exponential',
                  n_estimators=260, random_state=1)

In [35]:
predict_model(final_ada);

In [41]:
import numpy as np
lgbm_params = {'num_leaves': np.arange(10,200,10),
                        'max_depth': [int(x) for x in np.linspace(10, 110, num = 11)],
                        'learning_rate': np.arange(0.1,1,0.1)
                        }

tuned_lightgbm=tune_model(lightgbm, custom_grid=lgbm_params)

In [45]:
evaluate_model(tuned_lightgbm)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [26]:
predict_model(tuned_lightgbm);

In [27]:
final_lightgbm = finalize_model(tuned_lightgbm)
print(final_lightgbm)

LGBMClassifier(bagging_fraction=0.9, bagging_freq=2, boosting_type='gbdt',
               class_weight=None, colsample_bytree=1.0, feature_fraction=0.6,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=100, min_child_weight=0.001,
               min_split_gain=0.6, n_estimators=280, n_jobs=-1, num_leaves=70,
               objective=None, random_state=1, reg_alpha=0.1, reg_lambda=0.001,
               silent='warn', subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)

In [28]:
predict_model(final_lightgbm);